import re

from PIL import Image, ImageDraw

from .painter import (
    DEFAULT_FONT,
    Color,
    LinearGradient,
    get_font,
    get_text_size,
)
from .plot import (
    Canvas,
    Frame,
    RandomTriangleBg,
    RoundRectBg,
    TextBox,
    TextStyle,
    VSplit,
)
from .timezone import datetime_from_millis, request_now

SEKAI_BLUE_BG = RandomTriangleBg(True)
SEKAI_RED_BG = RandomTriangleBg(False, main_hue=0.05)

BG_PADDING = 20
WIDGET_BG_COLOR = (255, 255, 255, 150)
WIDGET_BG_RADIUS = 10
DIFF_COLORS = {
    "easy": (102, 221, 17, 255),
    "normal": (51, 187, 238, 255),
    "hard": (255, 170, 0, 255),
    "expert": (238, 68, 102, 255),
    "master": (187, 51, 238, 255),
    "append": LinearGradient((182, 144, 247, 255), (243, 132, 220, 255), (0, 0), (1, 1)),
}

PLAY_RESULT_COLORS = {
    "not_clear": (69, 67, 104, 255),
    "clear": (255, 226, 118, 255),
    "fc": (253, 167, 249, 255),
    "ap": (63, 230, 228, 255),
}

DEFAULT_WATERMARK = "Designed by Lunacha, generated by HarukiBot NEO"
WATERMARK_MIN_SIZE = 8
WATERMARK_MAX_LINES = 2
WATERMARK_LINE_SEP = 2
WATERMARK_RIGHT_OFFSET = int(16 - BG_PADDING * 0.5)
WATERMARK_BOTTOM_OFFSET = 16
WATERMARK_SHADOW_OFFSET = 1

CHARACTER_COLOR_CODE = {
    1: "#33aaee",
    2: "#ffdd44",
    3: "#ee6666",
    4: "#bbdd22",
    5: "#ffccaa",
    6: "#99ccff",
    7: "#ffaacc",
    8: "#99eedd",
    9: "#ff6699",
    10: "#00bbdd",
    11: "#ff7722",
    12: "#0077dd",
    13: "#ffbb00",
    14: "#ff66bb",
    15: "#33dd99",
    16: "#bb88ee",
    17: "#bb6688",
    18: "#8888cc",
    19: "#ccaa88",
    20: "#ddaacc",
    21: "#33ccbb",
    22: "#ffcc11",
    23: "#ffee11",
    24: "#ffbbcc",
    25: "#dd4444",
    26: "#3366cc",
    27: "#33ccbb",
    28: "#33ccbb",
    29: "#33ccbb",
    30: "#33ccbb",
    31: "#33ccbb",
    32: "#ffcc11",
    33: "#ffcc11",
    34: "#ffcc11",
    35: "#ffcc11",
    36: "#ffcc11",
    37: "#ffee11",
    38: "#ffee11",
    39: "#ffee11",
    40: "#ffee11",
    41: "#ffee11",
    42: "#ffbbcc",
    43: "#ffbbcc",
    44: "#ffbbcc",
    45: "#ffbbcc",
    46: "#ffbbcc",
    47: "#dd4444",
    48: "#dd4444",
    49: "#dd4444",
    50: "#dd4444",
    51: "#dd4444",
    52: "#3366cc",
    53: "#3366cc",
    54: "#3366cc",
    55: "#3366cc",
    56: "#3366cc",
}


def roundrect_bg(
    fill: Color = WIDGET_BG_COLOR,
    radius: int = WIDGET_BG_RADIUS,
    alpha: int | None = None,
    blur_glass: bool | None = None,
    blur_glass_kwargs: dict | None = None,
):
    """
    统一的半透明白色圆角矩形背景
    """
    if blur_glass is None:
        blur_glass = True
    if alpha is not None:
        fill = (*fill[:3], alpha)
    return RoundRectBg(fill, radius, blur_glass=blur_glass, blur_glass_kwargs=blur_glass_kwargs or {})


def wrap_watermark_text(text: str, font, max_width: int) -> list[str]:
    """
    优先按双空格分段换行，只在单段过长时才退回到段内拆分。
    """
    max_width = max(1, int(max_width))
    lines: list[str] = []
    for raw_line in str(text).split("\n"):
        if not raw_line:
            lines.append("")
            continue

        segments = [segment.strip() for segment in re.split(r" {2,}", raw_line) if segment.strip()]
        if not segments:
            lines.append("")
            continue

        current = ""
        for segment in segments:
            candidate = segment if not current else f"{current}  {segment}"
            text_w, _ = get_text_size(font, candidate)
            if current and text_w > max_width:
                lines.append(current)
                current = segment
                continue
            current = candidate

        if current:
            lines.append(current)

    final_lines: list[str] = []
    for line in lines:
        text_w, _ = get_text_size(font, line)
        if text_w <= max_width:
            final_lines.append(line)
            continue

        current = ""
        for ch in line:
            candidate = current + ch
            text_w, _ = get_text_size(font, candidate)
            if current and text_w > max_width:
                final_lines.append(current)
                current = ch
            else:
                current = candidate
        if current:
            final_lines.append(current)
    return final_lines or [""]


def build_watermark_layout(
    text: str,
    max_width: int,
    size: int,
    min_size: int = WATERMARK_MIN_SIZE,
    max_lines: int = WATERMARK_MAX_LINES,
) -> tuple[int, str]:
    """
    优先保留字号；当单行放不下时改为多行，必要时再小幅缩字。
    """
    max_width = max(1, int(max_width))
    font_size = max(min_size, int(size))
    while font_size > min_size:
        font = get_font(DEFAULT_FONT, font_size)
        wrapped_lines = wrap_watermark_text(text, font, max_width)
        if len(wrapped_lines) <= max_lines:
            return font_size, "\n".join(wrapped_lines)
        font_size -= 1
    font = get_font(DEFAULT_FONT, min_size)
    return min_size, "\n".join(wrap_watermark_text(text, font, max_width))


def get_watermark_render_spec(text: str, max_width: int, size: int) -> tuple[int, list[str], int, int]:
    """
    计算水印的字号、换行结果与实际占用尺寸。
    """
    font_size, wrapped_text = build_watermark_layout(text, max_width, size)
    font = get_font(DEFAULT_FONT, font_size)
    lines = wrapped_text.split("\n")
    text_w = max((get_text_size(font, line)[0] for line in lines), default=0)
    text_h = len(lines) * (font_size + WATERMARK_LINE_SEP) - WATERMARK_LINE_SEP
    return font_size, lines, text_w, text_h


def get_watermark_layout_width(canvas: Canvas) -> int:
    """
    获取当前正文内容宽度，用于限制水印宽度，避免水印把整体排版撑宽。
    """
    content_w, _ = canvas._get_content_size()
    if content_w > 0:
        return int(content_w)

    if canvas.w is not None:
        return max(1, int(canvas.w) - canvas.h_padding * 2 - canvas.h_margin * 2)
    return 1


def get_watermark_content_size(canvas: Canvas) -> tuple[int, int]:
    """
    获取当前正文区域尺寸，水印 footer 会在该尺寸基础上向下扩展。
    """
    content_w, content_h = canvas._get_content_size()
    if content_w <= 0 and canvas.w is not None:
        content_w = int(canvas.w) - canvas.h_padding * 2 - canvas.h_margin * 2
    if content_h <= 0 and canvas.h is not None:
        content_h = int(canvas.h) - canvas.v_padding * 2 - canvas.v_margin * 2
    return max(1, int(content_w)), max(1, int(content_h))


def add_watermark(canvas: Canvas, text: str = DEFAULT_WATERMARK, size=12):
    """
    在画布上添加水印
    """
    max_text_width = max(1, get_watermark_layout_width(canvas) - WATERMARK_SHADOW_OFFSET)
    font_size, lines, _, text_h = get_watermark_render_spec(text, max_text_width, size)
    wrapped_text = "\n".join(lines)
    content_w, content_h = get_watermark_content_size(canvas)
    footer_height = text_h + WATERMARK_BOTTOM_OFFSET + WATERMARK_SHADOW_OFFSET
    text_box_w = max_text_width + WATERMARK_SHADOW_OFFSET
    text_box_h = text_h + WATERMARK_SHADOW_OFFSET

    items = list(canvas.items)
    frame_canvas = Frame().set_content_align(canvas.get_content_align()).set_padding(0).set_size((content_w, content_h))
    footer = Frame().set_content_align("rb").set_padding(0).set_size((content_w, footer_height))
    footer_text = (
        TextBox(
            wrapped_text,
            TextStyle(
                font=DEFAULT_FONT,
                size=font_size,
                color=(255, 255, 255, 255),
                use_shadow=True,
                shadow_offset=(WATERMARK_SHADOW_OFFSET, WATERMARK_SHADOW_OFFSET),
                shadow_color=(75, 75, 75, 255),
            ),
            line_sep=WATERMARK_LINE_SEP,
            wrap=False,
            overflow="clip",
            use_real_line_count=True,
        )
        .set_size((text_box_w, text_box_h))
        .set_content_align("r")
        .set_padding(0)
        .set_omit_parent_bg(True)
    )
    footer.add_item(footer_text)

    root = VSplit().set_sep(0).set_item_align("rb").set_padding(0)
    canvas.set_items([])
    for item in items:
        frame_canvas.add_item(item)
    root.add_item(frame_canvas)
    root.add_item(footer)
    canvas.add_item(root).set_size(None)


def build_request_watermark_text(request, extra_suffix: str | None = None) -> str:
    timezone_name = None
    dt_value = None
    if isinstance(request, list | tuple):
        for item in request:
            timezone_name = getattr(item, "timezone", None)
            dt_value = getattr(item, "dt", None)
            if timezone_name is not None or dt_value is not None:
                break
    else:
        timezone_name = getattr(request, "timezone", None)
        dt_value = getattr(request, "dt", None)

    text = DEFAULT_WATERMARK
    if timezone_name is not None or dt_value is not None:
        dt = datetime_from_millis(dt_value, timezone_name)
        if dt is None:
            dt = request_now(timezone_name)
        timezone_label = (timezone_name or "").strip()
        if not timezone_label and dt.tzinfo is not None:
            timezone_label = dt.tzname() or ""
        if timezone_label:
            text = f"DT: {dt.strftime('%Y-%m-%d %H:%M:%S')} ({timezone_label})  {text}"
        else:
            text = f"DT: {dt.strftime('%Y-%m-%d %H:%M:%S')}  {text}"

    suffix = (extra_suffix or "").strip()
    if suffix:
        text = f"{text}  {suffix}"
    return text


def add_request_watermark(canvas: Canvas, request, extra_suffix: str | None = None, size=12):
    add_watermark(canvas, build_request_watermark_text(request, extra_suffix=extra_suffix), size=size)


def add_watermark_to_image(image: Image.Image, text: str = DEFAULT_WATERMARK, size=12) -> Image.Image:
    if image.mode != "RGBA":
        image = image.convert("RGBA")
    image = image.copy()
    max_text_width = image.width - WATERMARK_RIGHT_OFFSET
    font_size, lines, text_w, text_h = get_watermark_render_spec(text, max_text_width, size)
    font = get_font(DEFAULT_FONT, font_size)
    footer_height = text_h + WATERMARK_BOTTOM_OFFSET + WATERMARK_SHADOW_OFFSET
    sample_height = max(1, min(image.height, max(1, footer_height)))
    footer_bg = image.crop((0, image.height - sample_height, image.width, image.height))
    if footer_bg.height != footer_height:
        footer_bg = footer_bg.resize((image.width, footer_height), Image.Resampling.BILINEAR)

    output = Image.new("RGBA", (image.width, image.height + footer_height))
    output.paste(image, (0, 0))
    output.paste(footer_bg, (0, image.height))

    draw = ImageDraw.Draw(output)
    x = max(0, output.width - text_w - WATERMARK_RIGHT_OFFSET)
    y = max(0, image.height + footer_height - text_h - WATERMARK_BOTTOM_OFFSET)
    for idx, line in enumerate(lines):
        line_w, _ = get_text_size(font, line)
        line_x = x + max(0, text_w - line_w)
        line_y = y + idx * (font_size + WATERMARK_LINE_SEP)
        draw.text((line_x + 1, line_y + 1), line, font=font, fill=(75, 75, 75, 255))
        draw.text((line_x, line_y), line, font=font, fill=(255, 255, 255, 255))
    return output


def add_request_watermark_to_image(
    image: Image.Image,
    request,
    extra_suffix: str | None = None,
    size=12,
) -> Image.Image:
    return add_watermark_to_image(image, build_request_watermark_text(request, extra_suffix=extra_suffix), size=size)
