sonar.projectKey=Team-Haruki_Haruki-Drawing-API
sonar.organization=team-haruki
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
sonar.sources=src,scripts
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
