"""Standalone info panel (/api/pjsk/profile/info-panel): transparent canvas, PNG, two-line watermark."""

from io import BytesIO
from types import SimpleNamespace

from fastapi.testclient import TestClient
from PIL import Image
import pytest

from src.core.image_payload import EncodedImagePayload
from src.sekai.base import draw
from src.sekai.profile import drawer
from src.sekai.profile.model import ProfileCardRequest
from src.sekai.skia_renderer import canvas as canvas_mod

DT = 1790841600000  # 2026-10-01 16:00:00 Asia/Shanghai


def _request(**overrides) -> ProfileCardRequest:
    body = {
        "profile": {"id": "1234567890123456", "region": "JP", "nickname": "Panel", "leader_image_path": "avatar.png"},
        "rank": 300,
        "data_sources": [{"name": "Suite数据", "update_time": DT - 3_600_000}],
        "timezone": "Asia/Shanghai",
        "dt": DT,
    }
    body.update(overrides)
    return ProfileCardRequest.model_validate(body)


def test_dt_watermark_is_the_request_dt_over_the_credit():
    text = draw.build_request_dt_watermark_text(SimpleNamespace(timezone="Asia/Shanghai", dt=DT))
    assert text == "DT: 2026-10-01 16:00:00 (Asia/Shanghai)\nGenerated by HarukiBot NEO"
    assert draw.build_request_dt_watermark_text(SimpleNamespace()) == "Generated by HarukiBot NEO"


@pytest.mark.anyio
async def test_info_panel_defaults_to_an_opaque_card_but_keeps_an_explicit_alpha(monkeypatch):
    seen = []

    async def card(rqd):
        seen.append(rqd.bg_alpha)
        return drawer.Spacer(470, 120)

    monkeypatch.setattr(drawer, "get_profile_card", card)
    await drawer._build_info_panel_canvas(_request())
    await drawer._build_info_panel_canvas(_request(bg_alpha=90))
    assert seen == [drawer._INFO_PANEL_BG_ALPHA, 90]


@pytest.mark.anyio
@pytest.mark.parametrize("backend", ["skia", "pillow"])
async def test_info_panel_is_transparent_png_on_both_backends(tmp_path, monkeypatch, real_fonts, backend):
    monkeypatch.setattr(drawer, "ASSETS_BASE_DIR", tmp_path)
    monkeypatch.setattr(canvas_mod, "ASSETS_BASE_DIR", tmp_path)
    Image.new("RGBA", (128, 128), (20, 40, 60, 255)).save(tmp_path / "avatar.png")
    if backend == "skia":
        pytest.importorskip("haruki_skia_renderer")
        payload = await drawer.try_render_info_panel_payload(_request())
        assert payload is not None
        assert payload.image_bytes[:8] == b"\x89PNG\r\n\x1a\n"
        image = Image.open(BytesIO(payload.image_bytes))
    else:
        image = await drawer.compose_info_panel_image(_request())
    image = image.convert("RGBA")
    w, h = image.size
    assert image.getpixel((0, 0))[3] == 0  # canvas corner
    assert image.getpixel((w - 1, 0))[3] == 0
    assert image.getpixel((w // 2, h // 3))[3] > 200  # the card itself
    # the watermark sits under the card, right-aligned, on the transparent footer
    footer = image.crop((0, h - 30, w, h)).getchannel("A")  # the "Generated by" line
    left, _, right, _ = footer.getbbox()
    assert right > w - 60
    assert left > w // 3


def test_info_panel_route_pins_png(monkeypatch):
    from src.core.main import app
    from src.core.pjsk import profile as route

    async def render(_request):
        return EncodedImagePayload(
            image_bytes=b"\x89PNG\r\n\x1a\nfake",
            media_type="image/png",
            filename="info-panel.png",
            image_width=1,
            image_height=1,
            image_mode="RGBA",
            encode_elapsed=0.0,
        )

    monkeypatch.setattr(route, "try_render_info_panel_payload", render)
    response = TestClient(app).post("/api/pjsk/profile/info-panel", json=_request().model_dump())
    assert response.status_code == 200
    assert response.headers["content-type"] == "image/png"
