from .painter import (
    LinearGradient,
    Color,
    DEFAULT_FONT,
    )
from .plot import (
    RandomTriangleBg,
    RoundRectBg,
    Canvas,
    Frame,
    TextStyle,
    TextBox,
)

SEKAI_BLUE_BG = RandomTriangleBg(True)
SEKAI_RED_BG = RandomTriangleBg(False, main_hue=0.05)

BG_PADDING = 20
WIDGET_BG_COLOR = (255, 255, 255, 150)
WIDGET_BG_RADIUS = 10

DIFF_COLORS = {
    "easy": (102, 221, 17, 255),
    "normal": (51,187, 238, 255),
    "hard": (255, 170, 0, 255),
    "expert": (238, 68, 102, 255),
    "master": (187, 51, 238, 255),
    "append": LinearGradient((182, 144, 247, 255), (243, 132, 220, 255), (0, 0), (1, 1)),
}

DEFAULT_WATERMARK = "Designed & generated by NeuraXmy(ルナ茶)'s lunabot"


def roundrect_bg(fill: Color=WIDGET_BG_COLOR, radius: int=WIDGET_BG_RADIUS, alpha: int=None, blur_glass: bool=None, blur_glass_kwargs: dict={}):
    """
    统一的半透明白色圆角矩形背景
    """
    if blur_glass is None:
        blur_glass = True
    if alpha is not None:
        fill = (*fill[:3], alpha)
    return RoundRectBg(fill, radius, blur_glass=blur_glass, blur_glass_kwargs=blur_glass_kwargs)

def add_watermark(canvas: Canvas, text: str=DEFAULT_WATERMARK, size=12):
    """
    在画布上添加水印
    """
    frame_watermark = Frame().set_content_align("rb").set_padding(0)
    frame_canvas = Frame().set_content_align(canvas.get_content_align()).set_padding(0).set_size((canvas.w, canvas.h))
    s1 = TextStyle(font=DEFAULT_FONT, size=size, color=(255, 255, 255, 256))
    s2 = TextStyle(font=DEFAULT_FONT, size=size, color=(75, 75, 75, 256))
    offset1 = (int(16 - BG_PADDING * 0.5), 16)
    offset2 = (offset1[0] + 1, offset1[1] + 1)
    text1 = TextBox(text, style=s1).set_omit_parent_bg(True).set_offset(offset1)
    text2 = TextBox(text, style=s2).set_omit_parent_bg(True).set_offset(offset2)
    items = canvas.items
    canvas.set_items([])
    canvas.set_padding(BG_PADDING)
    for item in items:
        frame_canvas.add_item(item)
    frame_watermark.add_item(frame_canvas)
    frame_watermark.add_item(text2)
    frame_watermark.add_item(text1)
    canvas.add_item(frame_watermark).set_size(None)